
package WebPageCinema;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;


public class Horarios extends javax.swing.JFrame {
    
 
    ArrayList<PeliculasGuardadas> peliculas;
    ArrayList<Fecha>fechas;
    ArrayList<Funciones>funciones;
    ArrayList<Tarjetas>tarjetas;
    DefaultListModel<String> model = new DefaultListModel<>();
    WebPageCinema cc;
    int recog;
    int recogHorario;
    int k = 0;

    public Horarios(ArrayList<PeliculasGuardadas> peliculas, int recog,ArrayList<Fecha>fechas,ArrayList<Funciones>funciones,ArrayList<Tarjetas>tarjetas) {
        this.fechas = fechas;
        this.recog = recog;
        this.funciones = funciones;
        this.peliculas = peliculas;
        this.tarjetas = tarjetas;
        initComponents();
        setHorarios(recog);
        setHorarios2(fechas,k);
    }
    
    public void setHorarios(int recog) {
        if (recog == 1) {
            peliNameLbl.setText(peliculas.get(0).nombrePelicula);
            formatoLbl.setText(peliculas.get(0).formato);
            idiomaLbl.setText(peliculas.get(0).idioma);
            generoLbl.setText(peliculas.get(0).genero);
            clasificacionLbl.setText(peliculas.get(0).edades);
            ImageIcon img = new ImageIcon(peliculas.get(0).url);
            peliPicLbl.setIcon(img);
            sinopsisTxtA.setText(peliculas.get(0).sinopsis);
        } else if (recog == 2) {
            peliNameLbl.setText(peliculas.get(1).nombrePelicula);
            formatoLbl.setText(peliculas.get(1).formato);
            idiomaLbl.setText(peliculas.get(1).idioma);
            generoLbl.setText(peliculas.get(1).genero);
            clasificacionLbl.setText(peliculas.get(1).edades);
            ImageIcon img = new ImageIcon(peliculas.get(1).url);
            peliPicLbl.setIcon(img);
            sinopsisTxtA.setText(peliculas.get(1).sinopsis);
        } else if (recog == 3) {
            peliNameLbl.setText(peliculas.get(2).nombrePelicula);
            formatoLbl.setText(peliculas.get(2).formato);
            idiomaLbl.setText(peliculas.get(2).idioma);
            generoLbl.setText(peliculas.get(2).genero);
            clasificacionLbl.setText(peliculas.get(2).edades);
            ImageIcon img = new ImageIcon(peliculas.get(2).url);
            peliPicLbl.setIcon(img);
            sinopsisTxtA.setText(peliculas.get(2).sinopsis);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        peliPicLbl = new javax.swing.JLabel();
        peliNameLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblx = new javax.swing.JLabel();
        lblx1 = new javax.swing.JLabel();
        lblx2 = new javax.swing.JLabel();
        lblx3 = new javax.swing.JLabel();
        formatoLbl = new javax.swing.JLabel();
        generoLbl = new javax.swing.JLabel();
        clasificacionLbl = new javax.swing.JLabel();
        idiomaLbl = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        horarios = new javax.swing.JList<>();
        lblx4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sinopsisTxtA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        peliPicLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        peliNameLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        peliNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        peliNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        peliNameLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HORARIOS");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblx.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblx.setForeground(new java.awt.Color(255, 255, 255));
        lblx.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblx.setText("Formato:");

        lblx1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblx1.setForeground(new java.awt.Color(255, 255, 255));
        lblx1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblx1.setText("Genero:");

        lblx2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblx2.setForeground(new java.awt.Color(255, 255, 255));
        lblx2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblx2.setText("Clasificacion:");

        lblx3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblx3.setForeground(new java.awt.Color(255, 255, 255));
        lblx3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblx3.setText("Idioma:");

        formatoLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        formatoLbl.setForeground(new java.awt.Color(255, 255, 255));
        formatoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        generoLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        generoLbl.setForeground(new java.awt.Color(255, 255, 255));
        generoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        clasificacionLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        clasificacionLbl.setForeground(new java.awt.Color(255, 255, 255));
        clasificacionLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        idiomaLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idiomaLbl.setForeground(new java.awt.Color(255, 255, 255));
        idiomaLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton2.setText("Seleccionar Butacas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(horarios);

        lblx4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblx4.setForeground(new java.awt.Color(255, 255, 255));
        lblx4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblx4.setText("Sinopsis:");

        sinopsisTxtA.setEditable(false);
        sinopsisTxtA.setColumns(20);
        sinopsisTxtA.setRows(5);
        jScrollPane2.setViewportView(sinopsisTxtA);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(peliNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(peliPicLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblx3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idiomaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblx2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clasificacionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblx1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(generoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblx, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(formatoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblx4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(445, 445, 445)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(peliNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(peliPicLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblx, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(formatoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblx1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(generoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblx2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clasificacionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblx3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idiomaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblx4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        WebPageCinema wpc = new WebPageCinema(peliculas,fechas,funciones,tarjetas);
        wpc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SeleccionarHorario sh = new SeleccionarHorario(peliculas,fechas,recog,funciones,tarjetas);
        sh.setVisible(true);
        for (int i = 0; i < tarjetas.size(); i++) {
            System.out.println(tarjetas.get(i).nombreTarjetaHabiente);
        }
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    //FUNCION RECURSIVA DOS
    public void setHorarios2(ArrayList x,int k){
        horarios.setModel(model);
        if(k >= fechas.size()){
            System.out.println("recursividad terminada!!!");
            return;
        }
        if(fechas.get(k).nombrePelicula.equals(peliNameLbl.getText())){
            model.addElement(fechas.get(k).hora + ", " + fechas.get(k).fecha);
        }
        setHorarios2(fechas,k+1);
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clasificacionLbl;
    private javax.swing.JLabel formatoLbl;
    private javax.swing.JLabel generoLbl;
    private javax.swing.JList<String> horarios;
    private javax.swing.JLabel idiomaLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblx;
    private javax.swing.JLabel lblx1;
    private javax.swing.JLabel lblx2;
    private javax.swing.JLabel lblx3;
    private javax.swing.JLabel lblx4;
    private javax.swing.JLabel peliNameLbl;
    private javax.swing.JLabel peliPicLbl;
    private javax.swing.JTextArea sinopsisTxtA;
    // End of variables declaration//GEN-END:variables
}
