/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package WebPageCinema;

import static com.sun.java.accessibility.util.AWTEventMonitor.addActionListener;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javafx.scene.paint.Color;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author lopez
 */
public class SeleccionarHorario extends javax.swing.JFrame implements ActionListener {

    ArrayList<PeliculasGuardadas> peliculas;
    ArrayList<Fecha> fechas;
    ArrayList<Funciones> funciones;
    ArrayList<Tarjetas>tarjetas;
    int recog;
    int counterAsientos = 0;
    String asientosCliente;
    String sala,fecha,hora;
    String totalSend = "";
    int adultParse = 0;
    int ninoParse = 0;
    int terEdadParse = 0;
    DefaultListModel<String> model = new DefaultListModel<>();

    public SeleccionarHorario(ArrayList<PeliculasGuardadas> peliculas, ArrayList<Fecha> fechas, int recog, ArrayList<Funciones> funciones,ArrayList<Tarjetas>tarjetas) {
        initComponents();
        this.peliculas = peliculas;
        this.fechas = fechas;
        this.funciones = funciones;
        this.recog = recog;
        this.tarjetas = tarjetas;
        asientosCliente = "";
        setNombrePelicula();
        setHorarios();
        setPreciosLbls();
        addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cantAdulto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cantNino = new javax.swing.JTextField();
        cant3Edad = new javax.swing.JTextField();
        precioAdulto = new javax.swing.JLabel();
        precioNino = new javax.swing.JLabel();
        precio3Edad = new javax.swing.JLabel();
        subtotalAdulto = new javax.swing.JLabel();
        subtotalNino = new javax.swing.JLabel();
        subtotal3Edad = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        numeroAsiento = new javax.swing.JTextField();
        FilasCombo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        horarios = new javax.swing.JList<>();
        nombrePeliculaLbl = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cantAsientosSeleccionados = new javax.swing.JLabel();
        guardarAsiento = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        back = new javax.swing.JButton();
        salaLbl = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLayeredPane1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tipo de Boleto");

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cantidad");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Precio");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Subtotal");

        cantAdulto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Adulto");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Niño");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Tercera Edad");

        precioAdulto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        precioAdulto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        precioNino.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        precio3Edad.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        subtotalAdulto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subtotalAdulto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        subtotalNino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subtotalNino.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        subtotal3Edad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subtotal3Edad.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Total");

        total.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        submit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        submit.setText("OK");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Fila");

        FilasCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J" }));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Asiento");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(86, 86, 86)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cantNino, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cantAdulto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cant3Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(82, 82, 82))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(FilasCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(precioAdulto, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(precioNino, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(precio3Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(subtotal3Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(subtotalNino, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(subtotalAdulto, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1)
                                        .addGap(19, 19, 19))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(numeroAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(submit)
                                .addGap(29, 29, 29)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(subtotalAdulto, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                                        .addComponent(precioAdulto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cantAdulto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(subtotalNino, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                                    .addComponent(precioNino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(cantNino, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precio3Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cant3Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subtotal3Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numeroAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FilasCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(submit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setLayout(new java.awt.GridLayout(10, 20));

        jScrollPane1.setViewportView(horarios);

        nombrePeliculaLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nombrePeliculaLbl.setForeground(new java.awt.Color(255, 255, 255));
        nombrePeliculaLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Asientos Seleccionados:");

        cantAsientosSeleccionados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cantAsientosSeleccionados.setForeground(new java.awt.Color(255, 0, 0));

        guardarAsiento.setText("Guardar Asiento");
        guardarAsiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarAsientoActionPerformed(evt);
            }
        });

        jList1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jList1.setForeground(new java.awt.Color(204, 0, 0));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "A", " ", "B", " ", "C", " ", "D", " ", "E", " ", "F", " ", "G", " ", "H", " ", "I", " ", "J" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombrePeliculaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardarAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantAsientosSeleccionados, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1093, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(nombrePeliculaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantAsientosSeleccionados, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guardarAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        salaLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        salaLbl.setForeground(new java.awt.Color(204, 0, 0));

        jLabel12.setText("jLabel12");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(411, 411, 411)
                        .addComponent(salaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(salaLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );

        jLayeredPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        jPanel1.updateUI();
        System.out.println("Se ha borrado seats");
        for (int i = 0; i < funciones.size(); i++) {
            if (horarios.getSelectedValue().equals(funciones.get(i).horario)) {
                for (int j = 0; j < 1; j++) {
                    for (int k = 0; k < 20; k++) {
                        jPanel1.add(funciones.get(i).filaA[j][k]);
                    }
                }
                for (int j = 0; j < 1; j++) {
                    for (int k = 0; k < 20; k++) {
                        jPanel1.add(funciones.get(i).filaB[j][k]);
                    }
                }
                for (int j = 0; j < 1; j++) {
                    for (int k = 0; k < 20; k++) {
                        jPanel1.add(funciones.get(i).filaC[j][k]);
                    }
                }
                for (int j = 0; j < 1; j++) {
                    for (int k = 0; k < 20; k++) {
                        jPanel1.add(funciones.get(i).filaD[j][k]);
                    }
                }
                for (int j = 0; j < 1; j++) {
                    for (int k = 0; k < 20; k++) {
                        jPanel1.add(funciones.get(i).filaE[j][k]);
                    }
                }
                for (int j = 0; j < 1; j++) {
                    for (int k = 0; k < 20; k++) {
                        jPanel1.add(funciones.get(i).filaF[j][k]);
                    }
                }
                for (int j = 0; j < 1; j++) {
                    for (int k = 0; k < 20; k++) {
                        jPanel1.add(funciones.get(i).filaG[j][k]);
                    }
                }
                for (int j = 0; j < 1; j++) {
                    for (int k = 0; k < 20; k++) {
                        jPanel1.add(funciones.get(i).filaH[j][k]);
                    }
                }
                for (int j = 0; j < 1; j++) {
                    for (int k = 0; k < 20; k++) {
                        jPanel1.add(funciones.get(i).filaI[j][k]);
                    }
                }
                for (int j = 0; j < 1; j++) {
                    for (int k = 0; k < 20; k++) {
                        jPanel1.add(funciones.get(i).filaJ[j][k]);
                    }
                }
                System.out.println(funciones.get(i).horario);
            }
        }

        if (!cantAdulto.getText().equals("")) {
            subtotalAdulto.setText(String.valueOf(Integer.parseInt(precioAdulto.getText()) * Integer.parseInt(cantAdulto.getText())));
            adultParse = Integer.parseInt(cantAdulto.getText());
        } else if (cantAdulto.getText().equals("")) {
            subtotalAdulto.setText(String.valueOf(Integer.parseInt(precioAdulto.getText()) * 0));
            adultParse = 0;
        }

        if (!cantNino.getText().equals("")) {
            subtotalNino.setText(String.valueOf(Integer.parseInt(precioNino.getText()) * Integer.parseInt(cantNino.getText())));
            ninoParse = Integer.parseInt(cantNino.getText());
        } else if (cantNino.getText().equals("")) {
            subtotalNino.setText(String.valueOf(Integer.parseInt(precioNino.getText()) * 0));
            ninoParse = 0;
        }

        if (!cant3Edad.getText().equals("")) {
            subtotal3Edad.setText(String.valueOf(Integer.parseInt(precio3Edad.getText()) * Integer.parseInt(cant3Edad.getText())));
            terEdadParse = Integer.parseInt(cant3Edad.getText());
        } else if (cant3Edad.getText().equals("")) {
            subtotal3Edad.setText(String.valueOf(Integer.parseInt(precio3Edad.getText()) * 0));
            terEdadParse = 0;
        }

        if (!cantAdulto.getText().equals("")) {

        }
        counterAsientos = adultParse + ninoParse + terEdadParse;
        cantAsientosSeleccionados.setText(String.valueOf(counterAsientos));
        total.setText(String.valueOf(Integer.parseInt(subtotalAdulto.getText()) + Integer.parseInt(subtotalNino.getText()) + Integer.parseInt(subtotal3Edad.getText())));
        jPanel4.updateUI();
    }//GEN-LAST:event_submitActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Horarios hs = new Horarios(peliculas, recog, fechas, funciones,tarjetas);
        hs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        cantAdulto.setText("");
        cantNino.setText("");
        cant3Edad.setText("");
        subtotalAdulto.setText("");
        subtotalNino.setText("");
        subtotal3Edad.setText("");
        total.setText("");
        counterAsientos = 0;
        jPanel1.removeAll();
        jPanel1.updateUI();
        jPanel3.updateUI();
        jPanel4.updateUI();
        jPanel2.updateUI();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void guardarAsientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarAsientoActionPerformed
        
        counterAsientos--;
        cantAsientosSeleccionados.updateUI();
        for (int i = 0; i < funciones.size(); i++) {
            if (horarios.getSelectedValue().equals(funciones.get(i).horario)) {
                
                if (FilasCombo.getSelectedItem().toString().equals("A")) {
                    switch (Integer.parseInt(numeroAsiento.getText())) {
                        case 1:
                            funciones.get(i).filaA[0][0].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 2:
                            funciones.get(i).filaA[0][1].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 3:
                            funciones.get(i).filaA[0][2].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 4:
                            funciones.get(i).filaA[0][3].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 5:
                            funciones.get(i).filaA[0][4].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 6:
                            funciones.get(i).filaA[0][5].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 7:
                            funciones.get(i).filaA[0][6].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 8:
                            funciones.get(i).filaA[0][7].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 9:
                            funciones.get(i).filaA[0][8].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 10:
                            funciones.get(i).filaA[0][9].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 11:
                            funciones.get(i).filaA[0][10].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 12:
                            funciones.get(i).filaA[0][11].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 13:
                            funciones.get(i).filaA[0][12].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 14:
                            funciones.get(i).filaA[0][13].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 15:
                            funciones.get(i).filaA[0][14].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 16:
                            funciones.get(i).filaA[0][15].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 17:
                            funciones.get(i).filaA[0][16].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 18:
                            funciones.get(i).filaA[0][17].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 19:
                            funciones.get(i).filaA[0][18].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 20:
                            funciones.get(i).filaA[0][19].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                    }
                }else if(FilasCombo.getSelectedItem().toString().equals("B")){
                    switch (Integer.parseInt(numeroAsiento.getText())) {
                        case 1:
                            funciones.get(i).filaB[0][0].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 2:
                            funciones.get(i).filaB[0][1].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 3:
                            funciones.get(i).filaB[0][2].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 4:
                            funciones.get(i).filaB[0][3].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 5:
                            funciones.get(i).filaB[0][4].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 6:
                            funciones.get(i).filaB[0][5].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 7:
                            funciones.get(i).filaB[0][6].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 8:
                            funciones.get(i).filaB[0][7].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 9:
                            funciones.get(i).filaB[0][8].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 10:
                            funciones.get(i).filaB[0][9].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 11:
                            funciones.get(i).filaB[0][10].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 12:
                            funciones.get(i).filaB[0][11].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 13:
                            funciones.get(i).filaB[0][12].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 14:
                            funciones.get(i).filaB[0][13].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 15:
                            funciones.get(i).filaB[0][14].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 16:
                            funciones.get(i).filaB[0][15].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 17:
                            funciones.get(i).filaB[0][16].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 18:
                            funciones.get(i).filaB[0][17].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 19:
                            funciones.get(i).filaB[0][18].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 20:
                            funciones.get(i).filaB[0][19].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                    }
                }else if(FilasCombo.getSelectedItem().toString().equals("C")){
                    switch (Integer.parseInt(numeroAsiento.getText())) {
                        case 1:
                            funciones.get(i).filaC[0][0].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 2:
                            funciones.get(i).filaC[0][1].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 3:
                            funciones.get(i).filaC[0][2].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 4:
                            funciones.get(i).filaC[0][3].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 5:
                            funciones.get(i).filaC[0][4].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 6:
                            funciones.get(i).filaC[0][5].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 7:
                            funciones.get(i).filaC[0][6].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 8:
                            funciones.get(i).filaC[0][7].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 9:
                            funciones.get(i).filaC[0][8].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 10:
                            funciones.get(i).filaC[0][9].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 11:
                            funciones.get(i).filaC[0][10].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 12:
                            funciones.get(i).filaC[0][11].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 13:
                            funciones.get(i).filaC[0][12].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 14:
                            funciones.get(i).filaC[0][13].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 15:
                            funciones.get(i).filaC[0][14].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 16:
                            funciones.get(i).filaC[0][15].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 17:
                            funciones.get(i).filaC[0][16].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 18:
                            funciones.get(i).filaC[0][17].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 19:
                            funciones.get(i).filaC[0][18].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 20:
                            funciones.get(i).filaC[0][19].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                    }
                }else if(FilasCombo.getSelectedItem().toString().equals("D")){
                    switch (Integer.parseInt(numeroAsiento.getText())) {
                        case 1:
                            funciones.get(i).filaD[0][0].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 2:
                            funciones.get(i).filaD[0][1].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 3:
                            funciones.get(i).filaD[0][2].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 4:
                            funciones.get(i).filaD[0][3].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 5:
                            funciones.get(i).filaD[0][4].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 6:
                            funciones.get(i).filaD[0][5].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 7:
                            funciones.get(i).filaD[0][6].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 8:
                            funciones.get(i).filaD[0][7].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 9:
                            funciones.get(i).filaD[0][8].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 10:
                            funciones.get(i).filaD[0][9].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 11:
                            funciones.get(i).filaD[0][10].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 12:
                            funciones.get(i).filaD[0][11].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 13:
                            funciones.get(i).filaD[0][12].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 14:
                            funciones.get(i).filaD[0][13].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 15:
                            funciones.get(i).filaD[0][14].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 16:
                            funciones.get(i).filaD[0][15].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 17:
                            funciones.get(i).filaD[0][16].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 18:
                            funciones.get(i).filaD[0][17].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 19:
                            funciones.get(i).filaD[0][18].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 20:
                            funciones.get(i).filaD[0][19].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                    }
                }else if(FilasCombo.getSelectedItem().toString().equals("E")){
                    switch (Integer.parseInt(numeroAsiento.getText())) {
                        case 1:
                            funciones.get(i).filaE[0][0].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 2:
                            funciones.get(i).filaE[0][1].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 3:
                            funciones.get(i).filaE[0][2].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 4:
                            funciones.get(i).filaE[0][3].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 5:
                            funciones.get(i).filaE[0][4].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 6:
                            funciones.get(i).filaE[0][5].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 7:
                            funciones.get(i).filaE[0][6].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 8:
                            funciones.get(i).filaE[0][7].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 9:
                            funciones.get(i).filaE[0][8].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 10:
                            funciones.get(i).filaE[0][9].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 11:
                            funciones.get(i).filaE[0][10].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 12:
                            funciones.get(i).filaE[0][11].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 13:
                            funciones.get(i).filaE[0][12].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 14:
                            funciones.get(i).filaE[0][13].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 15:
                            funciones.get(i).filaE[0][14].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 16:
                            funciones.get(i).filaE[0][15].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 17:
                            funciones.get(i).filaE[0][16].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 18:
                            funciones.get(i).filaE[0][17].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 19:
                            funciones.get(i).filaE[0][18].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 20:
                            funciones.get(i).filaE[0][19].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                    }
                }else if(FilasCombo.getSelectedItem().toString().equals("F")){
                    switch (Integer.parseInt(numeroAsiento.getText())) {
                        case 1:
                            funciones.get(i).filaF[0][0].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 2:
                            funciones.get(i).filaF[0][1].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 3:
                            funciones.get(i).filaF[0][2].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 4:
                            funciones.get(i).filaF[0][3].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 5:
                            funciones.get(i).filaF[0][4].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 6:
                            funciones.get(i).filaF[0][5].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 7:
                            funciones.get(i).filaF[0][6].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 8:
                            funciones.get(i).filaF[0][7].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 9:
                            funciones.get(i).filaF[0][8].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 10:
                            funciones.get(i).filaF[0][9].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 11:
                            funciones.get(i).filaF[0][10].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 12:
                            funciones.get(i).filaF[0][11].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 13:
                            funciones.get(i).filaF[0][12].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 14:
                            funciones.get(i).filaF[0][13].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 15:
                            funciones.get(i).filaF[0][14].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 16:
                            funciones.get(i).filaF[0][15].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 17:
                            funciones.get(i).filaF[0][16].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 18:
                            funciones.get(i).filaF[0][17].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 19:
                            funciones.get(i).filaF[0][18].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 20:
                            funciones.get(i).filaF[0][19].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                    }
                }else if(FilasCombo.getSelectedItem().toString().equals("G")){
                    switch (Integer.parseInt(numeroAsiento.getText())) {
                        case 1:
                            funciones.get(i).filaG[0][0].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 2:
                            funciones.get(i).filaG[0][1].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 3:
                            funciones.get(i).filaG[0][2].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 4:
                            funciones.get(i).filaG[0][3].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 5:
                            funciones.get(i).filaG[0][4].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 6:
                            funciones.get(i).filaG[0][5].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 7:
                            funciones.get(i).filaG[0][6].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 8:
                            funciones.get(i).filaG[0][7].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 9:
                            funciones.get(i).filaG[0][8].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 10:
                            funciones.get(i).filaG[0][9].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 11:
                            funciones.get(i).filaG[0][10].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 12:
                            funciones.get(i).filaG[0][11].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 13:
                            funciones.get(i).filaG[0][12].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 14:
                            funciones.get(i).filaG[0][13].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 15:
                            funciones.get(i).filaG[0][14].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 16:
                            funciones.get(i).filaG[0][15].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 17:
                            funciones.get(i).filaG[0][16].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 18:
                            funciones.get(i).filaG[0][17].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 19:
                            funciones.get(i).filaG[0][18].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 20:
                            funciones.get(i).filaG[0][19].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                    }
                }else if(FilasCombo.getSelectedItem().toString().equals("H")){
                    switch (Integer.parseInt(numeroAsiento.getText())) {
                        case 1:
                            funciones.get(i).filaH[0][0].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 2:
                            funciones.get(i).filaH[0][1].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 3:
                            funciones.get(i).filaH[0][2].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 4:
                            funciones.get(i).filaH[0][3].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 5:
                            funciones.get(i).filaH[0][4].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 6:
                            funciones.get(i).filaH[0][5].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 7:
                            funciones.get(i).filaH[0][6].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 8:
                            funciones.get(i).filaH[0][7].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 9:
                            funciones.get(i).filaH[0][8].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 10:
                            funciones.get(i).filaH[0][9].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 11:
                            funciones.get(i).filaH[0][10].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 12:
                            funciones.get(i).filaH[0][11].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 13:
                            funciones.get(i).filaH[0][12].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 14:
                            funciones.get(i).filaH[0][13].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 15:
                            funciones.get(i).filaH[0][14].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 16:
                            funciones.get(i).filaH[0][15].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 17:
                            funciones.get(i).filaH[0][16].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 18:
                            funciones.get(i).filaH[0][17].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 19:
                            funciones.get(i).filaH[0][18].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 20:
                            funciones.get(i).filaH[0][19].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                    }
                }else if(FilasCombo.getSelectedItem().toString().equals("I")){
                    switch (Integer.parseInt(numeroAsiento.getText())) {
                        case 1:
                            funciones.get(i).filaI[0][0].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 2:
                            funciones.get(i).filaI[0][1].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 3:
                            funciones.get(i).filaI[0][2].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 4:
                            funciones.get(i).filaI[0][3].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 5:
                            funciones.get(i).filaI[0][4].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 6:
                            funciones.get(i).filaI[0][5].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 7:
                            funciones.get(i).filaI[0][6].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 8:
                            funciones.get(i).filaI[0][7].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 9:
                            funciones.get(i).filaI[0][8].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 10:
                            funciones.get(i).filaI[0][9].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 11:
                            funciones.get(i).filaI[0][10].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 12:
                            funciones.get(i).filaI[0][11].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 13:
                            funciones.get(i).filaI[0][12].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 14:
                            funciones.get(i).filaI[0][13].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 15:
                            funciones.get(i).filaI[0][14].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 16:
                            funciones.get(i).filaI[0][15].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 17:
                            funciones.get(i).filaI[0][16].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 18:
                            funciones.get(i).filaI[0][17].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 19:
                            funciones.get(i).filaI[0][18].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 20:
                            funciones.get(i).filaI[0][19].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                    }
                }else if(FilasCombo.getSelectedItem().toString().equals("J")){
                    switch (Integer.parseInt(numeroAsiento.getText())) {
                        case 1:
                            funciones.get(i).filaJ[0][0].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 2:
                            funciones.get(i).filaJ[0][1].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 3:
                            funciones.get(i).filaJ[0][2].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 4:
                            funciones.get(i).filaJ[0][3].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 5:
                            funciones.get(i).filaJ[0][4].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 6:
                            funciones.get(i).filaJ[0][5].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 7:
                            funciones.get(i).filaJ[0][6].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 8:
                            funciones.get(i).filaJ[0][7].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 9:
                            funciones.get(i).filaJ[0][8].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 10:
                            funciones.get(i).filaJ[0][9].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 11:
                            funciones.get(i).filaJ[0][10].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 12:
                            funciones.get(i).filaJ[0][11].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 13:
                            funciones.get(i).filaJ[0][12].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 14:
                            funciones.get(i).filaJ[0][13].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 15:
                            funciones.get(i).filaJ[0][14].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 16:
                            funciones.get(i).filaJ[0][15].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 17:
                            funciones.get(i).filaJ[0][16].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 18:
                            funciones.get(i).filaJ[0][17].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 19:
                            funciones.get(i).filaJ[0][18].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                        case 20:
                            funciones.get(i).filaJ[0][19].setBackground(java.awt.Color.red);
                            jPanel4.updateUI();
                            break;
                    }
                } 
            }
        }
        
        for (int i = 0; i < peliculas.size(); i++) {
            if(nombrePeliculaLbl.getText().equals(peliculas.get(i).nombrePelicula)){
                sala = peliculas.get(i).sala;
            }
        }
        for (int i = 0; i < funciones.size(); i++) {
            if(horarios.getSelectedValue().equals(funciones.get(i).horario)){
                hora = funciones.get(i).hora;
                fecha = funciones.get(i).fecha;
            }
        }
        asientosCliente += FilasCombo.getSelectedItem().toString() + numeroAsiento.getText() + ", ";
        totalSend = total.getText();
        if(counterAsientos <= 0){
            JOptionPane.showMessageDialog(null, "Asientos Guardados");
            Pago pago = new Pago(fechas,funciones,peliculas,tarjetas,asientosCliente,totalSend,horarios.getSelectedValue(),sala,hora,fecha,recog,nombrePeliculaLbl.getText());
            pago.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_guardarAsientoActionPerformed

    public void setPreciosLbls() {

        for (int i = 0; i < peliculas.size(); i++) {
            if (nombrePeliculaLbl.getText().equals(peliculas.get(i).nombrePelicula)) {
                precioAdulto.setText(String.valueOf(peliculas.get(i).precio));
                precioNino.setText(String.valueOf(peliculas.get(i).precioNino));
                precio3Edad.setText(String.valueOf(peliculas.get(i).precioTerEdad));
            }

        }
    }

    public void setHorarios() {
        horarios.setModel(model);
        for (int i = 0; i < fechas.size(); i++) {
            if (fechas.get(i).nombrePelicula.equals(nombrePeliculaLbl.getText())) {
                model.addElement(fechas.get(i).hora + ", " + fechas.get(i).fecha);
            }
        }
    }

    public void setNombrePelicula() {
        
        if (recog == 1) {
            nombrePeliculaLbl.setText(peliculas.get(0).nombrePelicula);
            salaLbl.setText(peliculas.get(0).sala);
        } else if (recog == 2) {
            nombrePeliculaLbl.setText(peliculas.get(1).nombrePelicula);
            salaLbl.setText(peliculas.get(1).sala);
        } else if (recog == 3) {
            nombrePeliculaLbl.setText(peliculas.get(2).nombrePelicula);
            salaLbl.setText(peliculas.get(2).sala);
        }
    }

    public void actionPerformed(ActionEvent e) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> FilasCombo;
    private javax.swing.JButton back;
    private javax.swing.JTextField cant3Edad;
    private javax.swing.JTextField cantAdulto;
    private javax.swing.JLabel cantAsientosSeleccionados;
    private javax.swing.JTextField cantNino;
    private javax.swing.JButton guardarAsiento;
    private javax.swing.JList<String> horarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nombrePeliculaLbl;
    private javax.swing.JTextField numeroAsiento;
    private javax.swing.JLabel precio3Edad;
    private javax.swing.JLabel precioAdulto;
    private javax.swing.JLabel precioNino;
    private javax.swing.JLabel salaLbl;
    private javax.swing.JButton submit;
    private javax.swing.JLabel subtotal3Edad;
    private javax.swing.JLabel subtotalAdulto;
    private javax.swing.JLabel subtotalNino;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
